name       : cracklib
version    : 2.9.7
release    : 7
source     :
    - https://github.com/cracklib/cracklib/releases/download/v2.9.7/cracklib-2.9.7.tar.bz2 : fe82098509e4d60377b998662facf058dc405864a8947956718857dbb4bc35e6
    - https://github.com/cracklib/cracklib/releases/download/v2.9.7/cracklib-words-2.9.7.bz2 : ec25ac4a474588c58d901715512d8902b276542b27b8dd197e9c2ad373739ec4
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : security.library
summary    : A ProActive Password Sanity Library
description: |
    The CrackLib package contains a library used to enforce strong passwords by comparing user selected passwords to words in chosen word lists.
setup      : |
    bunzip2 -dc $sources/cracklib-words-%version%.bz2 > cracklib-words
    %configure --disable-static --without-python
build      : |
    %make
install    : |
    %make_install
    install -dm00755 $installdir/usr/share/dict
    install -Dm00644 cracklib-words $installdir/usr/share/cracklib/cracklib-words
    ln -s /usr/share/cracklib/cracklib-words $installdir/usr/share/dict/cracklib-words
    ln -s /usr/share/cracklib/cracklib-words $installdir/usr/share/dict/words
    ln -s /usr/share/cracklib/cracklib-small $installdir/usr/share/dict/cracklib-small
    export LD_LIBRARY_PATH=/lib64:/usr/lib64:$installdir/usr/lib64
    export PATH=$installdir/usr/sbin:$PATH
    create-cracklib-dict -o $installdir/usr/share/cracklib/pw_dict $installdir/usr/share/dict/cracklib-words
